### ISSUE TITLE
RVM Ruby version differs from Gemfile

### ISSUE THREAD

**Issue by alexkutzke** [laylacodogno/leaf#26]
`.ruby-version` indicates: `2.3.0`
https://github.com/laylacodogno/leaf/blob/develop/.ruby-version#L1

`Gemfile` indicates: `ruby "2.3.3"`
https://github.com/laylacodogno/leaf/blob/develop/Gemfile#L8

**Comment by laylacodogno** [comment]
Fixed at [https://github.com/laylacodogno/leaf/pull/30](url)
