### ISSUE TITLE
RVM

### ISSUE THREAD

**Issue by alexkutzke** [laylacodogno/leaf#5]
Você esta utilizando o RMV (Ruby version manager)?

Se sim, é importante adicionar os arquivos `.ruby-version` e `.ruby-gemset` ao repositório. Por exemplo,

```ruby
# .ruby-version
2.3.0

#.ruby-gemset
leaf-dev
```

**Comment by laylacodogno** [comment]
Opa. Não estava usando não. mas vamos resolver isso sim, vou adicionar os itens.

**Comment by laylacodogno** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Finalização Sprint 2](https://trello.com/c/Vn25AG69/24-finalizacao-sprint-2)

**Comment by laylacodogno** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issues Sprint 2](https://trello.com/c/X9E0GCIO/26-issues-sprint-2)
